### ISSUE TITLE
Не прогружаются картинки

### ISSUE THREAD

**Issue by wtlz** [vandalsvq/confluence-cloud-1c#4]
```
Atlassian
JavaScript load error
We tried to load scripts but something went wrong.
Please make sure that your network settings allow you to download scripts from the following domain:
https://aid-frontend.prod.atl-paas.net
```

Платформа:
- 8.3.23.1688

Экспорт в Word работает с выгрузкой картинок, кнопка Вложения картинки показывает, но не открывает по клику в списке.

**Comment by wtlz** [comment]
<img width="828" alt="image" src="https://github.com/vandalsvq/confluence-cloud-1c/assets/32014902/62c335f9-ac0f-4b05-abd8-80e8730c978b">

**Comment by wtlz** [comment]
<img width="455" alt="image" src="https://github.com/vandalsvq/confluence-cloud-1c/assets/32014902/bd49c254-827d-4343-9136-fc372bc145ff">

**Comment by vandalsvq** [comment]
исправлено в 1.0.3.1
