### ISSUE TITLE
Не работают команды Экспорт в PDF (в фоне и на клиенте) 

### ISSUE THREAD

**Issue by wtlz** [vandalsvq/confluence-cloud-1c#5]
Дает выбрать путь для сохранения, но после выдает ошибку, и на клиент-серверной базе, и на файловой:
`При выполнении операции произошла ошибка:
Ошибка определения адреса размещения файла PDF. Код ошибки: 200 (<task>
   <name>Задача не найдена</name>
   <currentStatus>Задача не найдена</currentStatus>
   <elapsed>0</elapsed>
   <remaining>0</remaining>
   <percentComplete>100</percentComplete>
   <isSuccessful>false</isSuccessful>
   <isComplete>true</isComplete>
</task>);
Ошибка определения адреса размещения файла PDF. Код ошибки: 200 (<task>
   <name>Задача не найдена</name>
   <currentStatus>Задача не найдена</currentStatus>
   <elapsed>0</elapsed>
   <remaining>0</remaining>
   <percentComplete>100</percentComplete>
   <isSuccessful>false</isSuccessful>
   <isComplete>true</isComplete>
</task>)
{ConfluenceCloud1C ОбщийМодуль.confluence_ApiClientServer.Модуль(181)}:ВызватьИсключение ТекстОшибки;
{ConfluenceCloud1C Обработка.confluence_БазаЗнаний.МодульМенеджера(9)}:confluence_ApiClientServer.check_error(Результат, Ложь);
{(1)}:Обработки.confluence_БазаЗнаний.ЭкспортСтатьиPDFВФоне(Параметры[0],Параметры[1])
{ОбщийМодуль.ОбщегоНазначения.Модуль(5289)}:Выполнить ИмяМетода + "(" + ПараметрыСтрока + ")";
{ОбщийМодуль.ДлительныеОперации.Модуль(1419)}:ОбщегоНазначения.ВыполнитьМетодКонфигурации(ИмяПроцедуры, ПараметрыВызова);
{ОбщийМодуль.ДлительныеОперации.Модуль(1396)}:ВызватьПроцедуру(ВсеПараметры.ИмяПроцедуры, ВсеПараметры.ПараметрыПроцедуры);`

**Comment by vandalsvq** [comment]
исправлено в 1.0.3.1
